### ISSUE TITLE
use of \mathcal for inline mathematical operations

### ISSUE THREAD

**Issue by reyhanhgh** [pmichaillat/latex-presentation#4]
Hi Pascal,

I need to use `\mathcal` in some of my equations for certain functions and operators, but it doesn't seem to be working correctly. For example:

`$\mathcal{f} : \mathcal{x} \mapsto \mathcal{y}$`

It doesn't display `f` or `y`, although it works fine for `x`. Could this issue be related to specific hard-coded settings within the template? I haven't received any errors or warnings so far.

Thank you very much.

**Comment by pmichaillat** [comment]
This is not related to the template but is a property of `mathcal`. The standard font used for `\mathcal` does not include any lowercase characters, and the font used in the template (Euler font, provided by the `eucal` package) does not either. So this is why you cannot get calligraphic letters for `f` or `y` (I am not sure why `x` works). My guess is that if you use uppercase letters instead of lowercase, everything should work: `$\mathcal{F} : \mathcal{X} \mapsto \mathcal{Y}$`.


In case that is of interest, [here is a discussion](https://tex.stackexchange.com/questions/479/lowercase-mathcal) offering various workarounds to get lowercase calligraphic letters.

**Comment by reyhanhgh** [comment]
Thank you Pascal. No, it does not work with upercases of `f` and `y` either; that is why I thought it might be related to the template's settings. I also tried the workarounds suggested in the discussion you mentioned and several others. None of them worked.

**Comment by pmichaillat** [comment]
This is so strange. If you look at `presentation.tex`, line 99, there are some calligraphic uppercase letters: `$\mathcal{A} - \mathcal{B} + \mathcal{Z} / \mathcal{H}$`. And the letters render without problem, as showed in the slide with math in `presentation.pdf`. So I am not sure what the issue is in your presentation—but I don't think it comes from the template.

Let me know if you figure it out, I am curious to know what is happening.

**Comment by reyhanhgh** [comment]
Yes it is weird it works for `x` also. I do not know what is wrong with some of the lettres. 
Yes, I will update you here.
Thank you Pascal.

**Comment by reyhanhgh** [comment]
UPDATE: Hi Pascal. I tested the solution proposed [here](https://tex.stackexchange.com/questions/348901/how-to-get-lower-case-calligraphic-font-in-math-mode#:~:text=The%20%5Cmathbcal%20command%20is%20defined%20by%20mathalfa%20to%20choose%20the%20bold%20version%2C%20if%20available%2C%20but%20you%20don%27t%20need%20to%20use%20it%3A%20just%20%5Cmathcal%20is%20sufficient) and it works perfectly!

**Comment by pmichaillat** [comment]
I am glad you can get lowercase calligraphic letters with that method!
